### ISSUE TITLE
Fix: Update login endpoint

### ISSUE THREAD

**Issue by j0rgedev** [jorgevfx/svf-api#17]
The login endpoint is not working properly. It doesn't check if the password given in the request body matches the stored password and it only happens if the stored password has the default format. So, even if you give the wrong password, it still lets you in. To make sure nobody can get in without the right password, the endpoint should first use the checkCredentials function and then check for the default format password.

**Comment by Hunter2506** [comment]
The structure of the login endpoint has been successfully reorganized and fixed.
